### ISSUE TITLE
wac-cdn-bfdr.atlassian.com

### ISSUE THREAD

**Issue by mathurr016** [mathurr016/CA--pi#35]
https://wac-cdn-bfldr.atlassian.com/K3MHR9G8/at/w5vskc8pwrq5m5534bhmrt7/Atlassian_Service_Level_Agreement_Loom_update.pdf

**Comment by mathurr016** [comment]
Creating a basic website involves several steps. Here's a step-by-step guide to help you through the process:

### Step 1: Setting Up Your Development Environment
1. **Install a Text Editor**: You can use any text editor, but popular ones include Visual Studio Code (VS Code), Sublime Text, and Atom.
2. **Install a Web Browser**: Make sure you have a web browser like Google Chrome, Firefox, or Safari for testing your website.

### Step 2: Create the Project Structure
1. **Create a Project Folder**: Create a new folder for your website project. For example, `my-website`.
2. **Create HTML, CSS, and JavaScript Files**:
   - `index.html`: This will be your main HTML file.
   - `styles.css`: This will contain your CSS styles.
   - `script.js`: This will contain your JavaScript code.

### Step 3: Write the HTML
1. **Basic HTML Structure**: Open `index.html` and add the following code:
   ```html
   <!DOCTYPE html>
   <html lang="en">
   <head>
       <meta charset="UTF-8">
       <meta name="viewport" content="width=device-width, initial-scale=1.0">
       <title>My Basic Website</title>
       <link rel="stylesheet" href="styles.css">
   </head>
   <body>
       <h1>Welcome to My Website</h1>
       <p>This is a basic website.</p>
       <button id="clickMe">Click Me</button>
       <script src="script.js"></script>
   </body>
   </html>
   ```

### Step 4: Write the CSS
1. **Basic CSS Styling**: Open `styles.css` and add the following code:
   ```css
   body {
       font-family: Arial, sans-serif;
       margin: 0;
       padding: 0;
       display: flex;
       flex-direction: column;
       align-items: center;
       justify-content: center;
       height: 100vh;
       background-color: #f0f0f0;
   }

   h1 {
       color: #333;
   }

   p {
       color: #666;
   }

   button {
       padding: 10px 20px;
       font-size: 16px;
       cursor: pointer;
   }
   ```

### Step 5: Write the JavaScript
1. **Basic JavaScript Functionality**: Open `script.js` and add the following code:
   ```javascript
   document.getElementById('clickMe').addEventListener('click', function() {
       alert('Button clicked!');
   });
   ```

### Step 6: Run Your Website
1. **Open `index.html` in a Browser**:
   - You can open `index.html` in your web browser by double-clicking the file or dragging it into the browser window.
   - Alternatively, you can use a local development server like [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) in VS Code for a better development experience.

This will create a basic website with HTML, CSS, and JavaScript. You can expand and customize it further based on your needs.

### Additional Resources
- **HTML Tutorial**: [W3Schools HTML Tutorial](https://www.w3schools.com/html/)
- **CSS Tutorial**: [W3Schools CSS Tutorial](https://www.w3schools.com/css/)
- **JavaScript Tutorial**: [W3Schools JavaScript Tutorial](https://www.w3schools.com/js/)

Feel free to ask if you have any specific questions or need further assistance!
